version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
       POSTGRES_USER: jahanzaib
       POSTGRES_PASSWORD: 12345
       POSTGRES_DB: "test"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  mongodb:
    image: mongo:latest
    ports:
      - "20717:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  postgres_data:
  mongodb_data:


